# Generated by Django 5.2 on 2025-05-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0002_alter_member_roles_alter_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='members',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='roles',
        ),
        migrations.CreateModel(
            name='RosterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.member')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.role')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rosters.roster')),
            ],
            options={
                'unique_together': {('roster', 'role')},
            },
        ),
    ]
